Makefile
paper.bib
paper.tex

Here's a basic latex document, with a bibliography that should contain some useful citations.

Outline latex structure

---

requirements.txt

This made the figures build for me - I guess we should add in networkx and a few more things @hyanwong?

Initial requirements.txt

---

Makefile
paper.bib
paper.tex

This is a WIP, but might be worth merging if others want to work on the text.
Intro and abstract text are in a "getting there" state I think. Clumsy phrasing etc, but I think the narrative is starting to come together.
Any thoughts @JereKoskela @hyanwong?

New abstract + introduction, start of ARG explanation section

---

paper.bib
paper.tex

Working through background material

---

paper.bib
paper.tex

Small issues from read through

Minor fixes.

---

argutils/viz.py

A bit hacky, but I suspect some hand-tweaking ability would be generally useful. For instance:
```
import argutils
import matplotlib.pyplot as plt
tables = argutils.wh99_example()
tables.sort()
ts = tables.tree_sequence()
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10,10))
ax1.set_title("dot layout without X tweaks")
argutils.viz.draw(ts, ax1)
ax2.set_title("true times, tweaking X for nodes 0 and 2")
argutils.viz.draw(ts, ax2, use_ranked_times=False, tweak_x={0: -10, 2: 10})
```

When drawing ARGs, allow y times to be used and hand tweak X pos

---

paper.tex

Closes #55. We can always reopen a more targeted issue if we want to discuss polishing this.

Added Hudson vs big ARG figure

---

argutils/viz.py

Use metadata labels to make nodes labels comparable even after simplification. As per other figures, we default to ascii uppercase letters. Use like this:
```
import argutils
import matplotlib.pyplot as plt
ts = argutils.viz.label_nodes(argutils.sim_coalescent(4, 0.001, 1000, seed=123))
print(f"{ts.num_samples} samples, {ts.num_trees} trees")
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15,10))
argutils.viz.draw(ts, ax1, use_ranked_times=None)
argutils.viz.draw(ts.simplify(), ax2, use_ranked_times=None)
```

Add ability to label nodes

---

argutils/viz.py
requirements.txt

Fixes #75 for me, although I'm not entirely sure why!

Use pydot rather than pygraphviz, to produce deterministic results

---

argutils/ancestry.py

Add simplify_keeping_unary_in_coal

---

argutils/ancestry.py
argutils/tests.py

Closes #87
It didn't seem worth the effort of thinking through what a proper rate would be here, so I just chucked in a simple probability.

Add a ``recomb_proba`` arg to wright fisher sim.

---

argutils/ancestry.py
argutils/tests.py
paper.tex

Fix for the problem in the WF sims you pointed out earlier @hyanwong

Fix error in WF sim

---

paper.bib
paper.tex

Rough pass on this section which is good enough as a first draft. Rather than fixating on the detail here, I think it would be good to  plough on with drafting other sections and then circle back when we have a good picture of the overall narrative and how we want to structure it.

working through ARG representation section

---

paper.tex

Removed nodes from Figure 1 and tweaked the rate columns. I haven't changed the side-by-side hack because while putting all of this into one tikz diagram is probably doable, the result will be impossible to tweak further. 
Closes #96

Tweaks to Fig 1

---

paper.tex

I think we don't need to reference the later Fu paper here. Two refs is enough for this point.

Remove a ref

---

paper.bib
paper.tex

Here's the current draft text. Need to think about where it's going next. Still a WIP

Writing for pedigree section

---

illustrations/pedigree.svg

To match the description in the text

Label individuals in the pedigree

---

argutils/ancestry.py
argutils/tests.py

Closes #105
Tricky thing this WF simulator...

Fix bugs in WF sim.

---

argutils/viz.py
illustrations/ARG_recomb_node_deletion.py
illustrations/pedigree.py

This will allow us to set bespoke edge labels easily

Return both the positions and the graph from draw

---

Makefile
illustrations/ARG_edge_annotations.py
paper.tex

I haven't put all the figure producing code into a single script yet, sorry @jeromekelleher, but it's all as little functions, so should be easy to port.

Initial pass at fig 4

---

argutils/ancestry.py
argutils/tests.py
illustrations/ARG_recomb_node_deletion.svg
paper.tex

First stab at ancestry resolution text

---

paper.tex

Simplification is too big a thing to mush together with ancestry resolution. Making a separate section for it.
WIP

Add separate simplification section

---

illustrations/ARG_recomb_node_deletion.py

Swap O and N labels

---

paper.tex

Light edit on start of EARG section

---

argutils/ancestry.py
illustrations.py
illustrations/assets/pedigree.svg

Update fig 3 to greyscale

---

paper.tex

Minor tweak here to the text.
The narrative doesn't quite sync up now, though, as we're talking about the GARG. Maybe the thing to do is move the criticism of the event-based encoding into the GARG section.

Small update to EARG section

---

illustrations.py
illustrations/assets/pedigree.svg
paper.tex

I think this describes what is now shown in fig 3.

Changes for fig3 caption

---

illustrations.py
paper.tex

Use "immediate inheritance" vs "sample resolved annotations".

Improve the caption for fig 4

---

paper.bib
paper.tex

Some citations and notes.

---

paper.tex

Fix up discussion of fig 3

---

argutils/convert.py
argutils/tests.py
examples/kreitman.kwarg

#133 Not thoroughly tested yet! Seems to work on the kreitman example (which I've added to the examples folder).

Convert function for KwARG output

---

illustrations.py
requirements.txt

Mostly fixes #123: needs tweaking for X labels and alignment, and also (ideally) to reorder the tips in the tree seqs to read ABCD.

Fig 5 plot all 4 tree seqs

---

paper.bib
paper.tex

Here's a start on a section discussing the relationship between ARGs and SPRs. I think we have to tackle this, as it's a fundamental property. I also want to address the (casually made, usually) assertion that an ARG is equivalent to a set of trees. What properties to these trees need to have in order to recover the graph?
I think there's two cases:
1. All nodes in the trees are **labelled** (and the labels correspond to the ARG node, obvs): easy
2. Nodes are *not* labelled: requires figuring out what the SPR between each pair of trees *must have been* and reasoning about the node identities based on that. This seems quite hard to me.
Also, unless there's unary nodes stored or some sort of out-of-band info attached, we can never know the exact times of the recombination events.
Does this …

Discussion of SPRs

---

illustrations.py

Move nodes in fig 5 to reveal lines properly

---

argutils/convert.py

This was failing on some argweaver outputs. Now we set more sensible times

Correct logic in argweaver convert

---

illustrations.py

Fig 4 tweaks to fix node images being cut off

---

argutils/viz.py
illustrations.py

Here's what I've done so far with visualizing breakpoints in Figure 6:
Below each of the inferred ARGs, I've stacked all the edges (sorted by edge start position and then edge end position), and added dashed vertical lines to indicate where breakpoints are. This shows how the ARGs change as you go along, and highlights some interesting similarities and differences between the outputs (in particular, what a JBOT actually is).
Here's another version I was experimenting with, where all the edges are labeled, and the breakpoints are also labeled below. I haven't shown this with Figure 6 because there are too many edges to actually label them.
And here's a simpler version of breakpoint visualization: simple, alternating black and grey rectangles. Here, the numbers indicate the number of edge …

Add breakpoints to fig 6

---

paper.tex

Along with Fig 1 and the phylo network discussion.
WIP. This is the big restructing as discussed in #198. Needs the section on *Ancestry resolution* revising to flow better.

Move Hudson discussion into later section

---

argutils/viz.py
illustrations.py
illustrations/assets/pedigree.svg
paper.tex

Just doing a pass through the first section, and I made a few minor changes. I thought I should PR these before moving to the next section.
Depends on the resolution to #206

Minor text changes

---

paper.tex

Fixes #209 and a few readability fixes

More minor tweaks

---

illustrations.py
paper.tex

Some minor tweaks made during a read through.

Minor updates

---

paper.bib
paper.tex
requirements.txt

I have done a pass to say more about the ag datasets - their scale and low Ne due to selection and massive use of just few sires.
I have noticed some other typos and inconsistencies too.

A pass on the ag datasets and some other edits

---

paper.tex

I have removed the stochastic processes section by moving some parts to the discussion and commenting out some of the parts that were not moved. Please do read through the intro and the first 4 paras of the "Event ARG data structure" section to see if it still flows and makes sense.
The idea here is to get quickly to the eARG stuff without distracting the reader too much with the history (although we do need a little of that).

Args as stochastic processes removal

---

paper.tex

I've been ruthless here and commented a lot of technical stuff out, in an attempt to make this section both shorter and more accessible. We can uncomment the paragraphs that we think are needed in the main text. All feedback welcome.
When completed, is intended to fix #212

Rephrase "Ancestry Resolution"

---

paper.tex

And stick some intermediate headings in to make the logic clearer to ourselves (these can be removed later if need be). My attempt to fix #234

Reorder event section

---

paper.tex

A proposed redraft of the ASG paragraph. The content is essentially unchanged but I tried to reshuffle things to emphasize "process-ness".

ASG redraft

---

paper.bib
paper.tex

Trying to tie in with previous sections, while not getting bogged down in details about which direction inheritance goes.

Pass through gARG section

---

paper.tex

Trying to give this more of a narrative.
I wonder if the Wiuf and Hein example might end up being a bit confusing, since it's really showing properties of a Big ARG. But, I guess people will be confused about this stuff so all we can do is try to tackle it and explain what's going on.

Pass through ancestry resolution section

---

paper.tex

Here's a proposal for the authorship list (as discussed on Slack)
Ping @hyanwong @a-ignatieva @JereKoskela @gregorgorjanc @awohns - can you check your affils please?
Please do should out if you don't agree with this!

Authorship

---

paper.tex

And also to introduce the idea of local trees early on.

Minor rephrasing to reduce word count

---

paper.tex

Correct the caption for Fig3

---

requirements.txt

tskit needs to be at least 0.5.1 to make the figures

Update required tskit

---

argutils/viz.py
illustrations.py
paper.tex

Involves reversing the coordinates in Fig 4. I tried squeezing the captions in without changing the size of the plots, but it might look a bit cramped.

Add a caption to figs 4 and 5

---

paper.tex

Fixed rates in ARG description

---

paper.tex

Closes #285
Lacks polish, but I think the basic elements of what we want is in there?

New abstract

---

argutils/convert.py

As a result of a conversation with Trevor Cousins.

Add fix and better output for ARGweaver conversion

---

paper.bib
paper.tex

Wilders comments

---

paper.bib
paper.tex

Attempt at #305
This is a bit bloated currently as it's very much a first pass at getting stuff on paper, but I feel like this gives us a natural way to say a few things that feel a bit strained otherwise. I'm sure most popgen people won't get that these vast and incredibly detailed ARGs exist and have been inferred unless we spell it out for them, and that's an important thing to be aware of (I think anyway).
Any thoughts on how it's looking before I merge (and sync with overleaf)?

First pass at sc2 narrative

---

argutils/convert.py

This allows them to be visualised properly using https://github.com/kitchensjn/tskit_arg_visualizer

Flag up kwarg RE nodes using the msprime flags

---

illustrations.py

Fixes https://github.com/tskit-dev/what-is-an-arg-paper/issues/341

Remove accidental ts3 dump

---

paper.tex

Fixes the bug in Figure 6, with a few cosmetic improvements in the surrounding section.
Closes #358

Fig 6 fixed

---

paper.tex

Closes #319
Also tries to spell out what the ARG viz stuff means and why you should care
A first pass, but hopefully moving in the right direction

Add description of simulation

---

paper.tex

Fix whitespace

---

paper.bib
paper.tex

Updates following up on various Kuhner papers.
The major change is in the "local trees" section

Discuss Kuhner

---

paper.bib
paper.tex

Add SCAR paper

---

argutils/convert.py

Came up when looking at viz (resulted in missing edges)

Bug fix: need to check which edge is left and which is right

---

paper.tex

WIP, trying to make the intro flow better and get to the point. The "problem" bit is currently very vague.

Content reshuffle

---

paper.tex

units stuff wasn't really working, easier to just typeset by hand

Remove SI units

---

paper.tex

A work in progress on the local trees section, trying to spell out why we think using a combinatorial encoding is useful and important.
Needs more work, but actually this seems quite an important insight...

Restructure "local trees" section

---

paper.tex

Substantial rewrite of intro, pushing new "definition based" perspective

Pass through intro

---

paper.tex

Trim some duplication of content, and remove strong assertions about identifiability etc. We don't want to get into discussions about what is observable or not, as that's contingent on a whole bunch of stuff we're not considering. We just want to point out the operations and their results.

Edits for s5 through s7

---

paper.bib
paper.tex

I've rejigged the "example inferred ARGs" section quite a bit here. Basic ideas:
- I tried to make the paragraphing more logical, with clear ideas in each one
- The method descriptions in the figure caption weren't very enlightening, so I moved them into the text to allow for a reasonable summary. We still need a description of Relate, which I'm hoping Ana will do.
- I've tried to cut down the number of things we're discussing to something manageable, so the reader has some chance of digesting it.

Substantial rejig of s9

---

paper.bib
paper.tex

Here's a draft of an introductory paragraph, with a new narrative angle, trying to tease apart the different concepts. We'd need to make a few more changes elsewhere and to reparagraph the introduction, so leaving it like this for now to see what people think.

First-pass at new intro narrative

---

paper.bib
paper.tex

making the case for shared software a bit more slowly. Also misc minor updates.

New last para

---

paper.tex

Rewritten abstract to follow new narrative

Abstract and address peters comments

---

paper.tex

Update intro and abstract

---

paper.bib
paper.tex

Move a bunch of material around

Reorder append

---

paper.bib
paper.tex

Rework "diversity" section narrative

---

paper.tex

Cut down to data policy statement

---

paper.tex

Closes #458 by cutting the sentence. It's not worth the bother

Cut bit about approx structures

---

Makefile
genetics.bst
gsajnl.cls
paper.tex
styles/goi.sty
styles/gos.sty
styles/gs.sty
styles/inv.sty
styles/mp.sty

Minimal changes for genetics format. Some figures look at bit crap in 2 column format, but let's worry about fixing that if it gets accepted.

Genetics format
