tskit-dev/what-is-an-arg-paper

utils/args.py

Here's a very rough simulator for ARGs in the Wright Fisher process. It was quite the mindy-bendy task, but well worth it I think.
The main thing I've gotten from this is a sense that the "standard" ARG (unsurprisingly) derives very closely from the CwR process, and it's particular structure owes a lot to the assumptions made in that process. The neat classification of nodes that you get from the coalescent really  doesn't hold any more when you have a small population WF process.
Basically you get everything happening at once in all possible combinations in the simulation. 
```
27.00┊   87       ┊            ┊            ┊            ┊                                                                                                                          
┊ ┏━━┻━━┓    ┊            ┊ …
```

Wright-Fisher ARG simulator

---

utils/args.py

I was wrong earlier that you could optionally include the parent nodes in a recombination event when we are associating the flags with the child node.
We *must* add the parent nodes and update the lineages, or we can have multiple recombination events hitting the same node/lineage. If you'd like to try it out, you can easily comment out chunks of code and see how the asserts trip.
You also must use two different parent nodes.

Fix recombination nodes.

---

paper.bib
paper.tex

I think the first sentence can be modified to better describe how evolutionary trees are practically used. I see the main categories of tree inference as: (1) species trees, (2) trees of non-recombining sections of genome, and (3) viral phylogenies. Do others like this classification?
Another reason to rephrase: we can't really cite viral phylogenetics papers with the current wording since viruses aren't usually referred to as "organisms".

Modified first sentence, added references

---

paper.bib
paper.tex

Mathieson & Scally (2020) is cited as an example of the "ARG as a subset of the pedigree" analogy. A literature search turns up two other solid citations for this analogy:
Gusfield (2014), Section 1.2:
>**Tracing the transmission history of sequences** Now consider an individual in a population and just one of the homologs of a homologous pair of some
chromosome (say from chromosome 21). The sequence on that homolog was
transmitted to the individual from just one parent, and since there is no recombination, that sequence was passed down from exactly one grandparent, etc. It
follows that the transmission history of the chromosome sequence forms a path
through ancestors in the individual’s pedigree. That path begins at a founder
sequence and descends to the individual. Further, since we …

add citations for pedigree arg relationship

---

argutils/__init__.py
argutils/__main__.py
argutils/ancestry.py
argutils/tests.py
argutils/viz.py

Two new things here:
1. It turns out that the resolve algorithm *is* actually simplify(keep_unary=True). I had been confused about what happens over the roots, but #61 has shown that simplify is actually doing the right thing. I haven't been able to find a counter example where it doesn't, but it must be right.
2. Put some simple infrastructure in for playing with visualisation by porting some of Yan's code. Now, running 
```
python3 -m argutils draw tmp.trees tmp.png
```
will draw a simple plot to the file. Currently it looks like this:
The layout looks good (although, not clear why node 4 is at the same y value as 7 and 8 - the time is different), but there's clearly plenty that could be done. The edge information is stored in the nx Graph object, so that should be sufficient to start …

Refine argutils

---

argutils/ancestry.py
argutils/tests.py

Adds the Wiuf and Hein 99 example ARG mentioned in #56.
The draw method currently produces this:
Here are the trees:
```
14.00┊  22   ┊  22   ┊  22   ┊    22  ┊  22    ┊
┊   ┃   ┊   ┃   ┊   ┃   ┊     ┃  ┊   ┃    ┊
13.00┊   ┃   ┊  21   ┊  21   ┊    21  ┊  21    ┊
┊   ┃   ┊   ┃   ┊  ┏┻━┓ ┊   ┏━┻┓ ┊ ┏━┻━┓  ┊
12.00┊  19   ┊  20   ┊ 20  ┃ ┊  20  ┃ ┊ 20  ┃  ┊
┊   ┃   ┊   ┃   ┊  ┃  ┃ ┊   ┃  ┃ ┊ ┃   ┃  ┊
11.00┊  18   ┊  18   ┊ 18  ┃ ┊  18  ┃ ┊ 18  ┃  ┊
┊   ┃   ┊   ┃   ┊  ┃  ┃ ┊ ┏━┻┓ ┃ ┊ ┃   ┃  ┊
10.00┊   ┃   ┊   ┃   ┊  ┃ 17 ┊ ┃  ┃17 ┊ ┃  17  ┊
┊   ┃   ┊   ┃   ┊  ┃  ┃ ┊ ┃  ┃ ┃ ┊ ┃  ┏┻┓ ┊
9.00 ┊   ┃   ┊   ┃   ┊  ┃  ┃ ┊ ┃ 15 ┃ ┊ ┃ 16 ┃ ┊
┊   ┃   ┊   ┃   ┊  ┃  ┃ ┊ ┃  ┃ ┃ ┊ ┃  ┃ ┃ ┊
8.00 ┊  14   ┊  14   ┊ 14  ┃ ┊ 14 ┃ ┃ ┊ 14 ┃ ┃ ┊
┊  ┏┻━┓ ┊  ┏┻━┓ ┊  ┃  ┃ ┊ ┃  ┃ ┃ ┊ ┃  ┃ ┃ ┊
7.00 ┊  ┃  ┃ ┊  ┃  ┃ ┊  ┃ …
```

Add Wiuf and Hein 99 example ARG

---

argutils/ancestry.py
argutils/tests.py

This changes the encoding for the "implicit" ARG to use (0, L) instread of +/- infinity, and thereby making the descriptions a valid tree sequence. This works really well, I think. Consider the trees we get when we draw the wh99 example:
```
14.00┊           22         ┊              22      ┊              22      ┊              22      ┊              22      ┊              22      ┊              22      ┊
┊       ┏━━━━┻━━━━┓    ┊           ┏━━━┻━━━━┓ ┊           ┏━━━┻━━━━┓ ┊           ┏━━━┻━━━━┓ ┊           ┏━━━┻━━━━┓ ┊           ┏━━━┻━━━━┓ ┊           ┏━━━┻━━━━┓ ┊
13.00┊       ┃        21    ┊          21        ┃ ┊          21        ┃ ┊          21        ┃ ┊          21        ┃ ┊          21        ┃ ┊          21        ┃ ┊
┊       ┃       ┏━┻━━┓ ┊       ┏━━━┻━━━┓    ┃ ┊ …
```

Change to (0,L) for ARG boundaries

---

argutils/ancestry.py
argutils/tests.py

Separate resolve() method is superfluous, and it's more convenient to return a tree sequence when ``resolve=False``.

Remove resolve() method and return tree sequence

---

argutils/viz.py

This allows us to place nodes in the same position in adjacent plots. It could also act as a workaround for #75 as we could output the positions and then hard code them. Here's how we could do the former:
```
ts = argutils.sim_coalescent(4, 0.001, 1000, seed=123)
print(f"{ts.num_samples} samples, {ts.num_trees} trees")
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20,10))
pos = argutils.viz.draw(ts, ax1, use_ranked_times=True, tweak_x={24: 15, 23: 5, 22: 10, 21: 10})
new_ts, node_map = ts.simplify(map_nodes=True)
_ = argutils.viz.draw(new_ts, ax2, pos={node_map[i]:p  for i, p in pos.items()})
```

Return positions from draw, and allow positions to be specified

---

argutils/ancestry.py
argutils/tests.py

Implement `test_simplify_keeping_all_nodes`, `simplify_remove_pass_through` (with option to repeatedly apply until no pass through nodes remain), and tidy up test_simplify_keeping_unary_in_coal so that it runs OK on tree sequences with individuals already present (e.g. for WF simulations).
The `simplify_remove_pass_through` function turned out to be a bit tricky. I think I have it right though, and there are tests for all this.

Implement 3 new types of simplification

---

argutils/viz.py

I can't see the text labels in the graph plots, and often the nodes are too small. This parameterises them. I suggest we use
`mpl.colors.to_hex(mpl.pyplot.cm.tab20(1))` as the default colour:

Allow size & colour of nodes to be set in viz

---

paper.tex

I'm not sure if this works or not, but I think it is much clearer if we switch to "big ARG" vs "little ARG" terminology as soon as possible, because we bandy the word "ARG" around when talking about Griffiths stuff, and it gets pretty confusing (to me, at least).
This is my attempt to try that out, but I'm not sure if it seems too clunky or not.

Mention "big" vs "little" ARG earlier

---

illustrations/ARG_recomb_node_deletion.py

See https://github.com/tskit-dev/what-is-an-arg-paper/issues/82#issuecomment-1039268250
There's an interesting case here where in (c) we haven't removed the ARG nodes in which multiple lines come together (i.e. node `I`).
~Annoyingly, I just realised, however, that this *doesn't* have any nodes that are both recombination and ca/coalescence nodes (apart from `J` which gets simplified away), so I might need to hunt for another example.~ Actually, node `E` is one of the 2 nodes that contribute to a "recombinant" and also a coalescent node. But maybe we want an example where a node is both a coalescent node and a *recombinant*.

Use W-F simulator for fig 5

---

paper.tex

A few small updates:
- Added a comment to the end of the intro section explaining that we only focus on discrete genomes and a single chromosome. It's currently a bullet point aimed at going into the end of a roundup paragraph. I think that would be a good place for it: it will tell specialists what to expect, but I think it is still non-technical enough that non-specialists shouldn't be confused. I'm open to opinions on whether it should go elsewhere though, or if it is needed to begin with.
- Slightly tweaked the spacing in Fig 1 to make lines not overlap now that it has been scaled down.
- Made Fig 1 consistent with the notation in the surrounding text (`m` rather than `L` for genome length), and made it work with discrete sites. This makes the recombination rates bulkier, but avoids …

Clarified single chr scope and unified Fig1 with text

---

paper.tex

I don't think we need to back refer to fig 2 any more here, as fig 3 is where we now introduce the 2-RE-node idea. I have also moved the formal definition of a gARG nearer the top of that section. Comments etc welcome - there are many improvements that could be made to my text, I'm sure.
This closes #140

Reword the 2 node recombination section

---

paper.tex

Uses `A`, `B`, `C` instead of 1, 2, 3 for fig 2. I'm not sure which I prefer. 1, 2, 3 is perhaps simpler to explain mathematically, but `A` `B` `C` is what we use for the rest of the figures, and labels the nodes using a different scheme from the edges (i.e. distinguishes "0" in the edge column from "0" in the node column).
I'm not sure what the norm is for ARG pictures and for mathematical graphs: possibly numbers?
Not to merge until we decide what we prefer. I had to do this for the ARG talk, so thought I might as well PR it too.

Change fig 2 to letter labels

---

illustrations.py
paper.tex

And updated caption. It now looks like this, which I think is better, and has fewer trees.
Also fixes #193 and  #166 and #182

Better example for fig 5

---

paper.tex

It's slightly clumsy having the graph in the middle when describing A, B, C, but I think it's visually best this way.

Update Fig 1 caption to refer to A, B, C

---

paper.tex

A first pass at shortening the sampling probability description and merging it with the inference methods section. I've left in the notation because I thought the description became more confusing without it, but pretty much all actual detail has been cut. Comments very welcome.
Closes #223

Sampling probabilities rewrite

---

paper.tex

A first draft of the appendix. I also added reference sentences to it in the main text when we bring up either stochastic processes or sampling probabilities, and slightly shuffled things in Figure 6 to facilitate making it a bit bigger.
I've used the terms "big ARG process" and "little ARG process" to talk about the Griffiths and Hudson processes, to avoid adding to the confusion about using just "ARG" for both the data structure and for a stochastic process. It didn't feel right to call them the "big" and "little coalescent with recombination", because that gets quite cumbersome.

ARG process appendix

---

paper.tex

We need to tackle the issue of node-vs-edge annotations, so the simplest thing to do is just give it a section. This seems like the logical place.

Add section on Node-vs-edge annotations

---

paper.tex

Added some new sections trying to cover the high-level points we want to discuss and putting in some outline text.
I moved the "ARG inference methods" text to an appendix, because it didn't really fit in with the narrative I've been trying to develop. I think it *is* really useful to classify the methods and list them out like this, so I think an appendix that we can refer to is a good option.

Args and trees

---

paper.tex

Closes #256 #251
In an attempt to shorten things down and make the text a bit snappier (as discussed in #256) I've merged the aARG and gARG sections.
I've been quite ruthless about cutting stuff out, but kept most of the old content commented out so we can merge bits of it back in later.
I've probably gone too far with the cutting, but how does the new outline look?

Merge eARG and gARG sections

---

paper.tex

I think the only common ancestors that are present in the simplified TS will be o and v

Remove description of W&H node u as a MRCA

---

paper.tex

We agreed at some point that it could be confusing to use "local inheritance" as a term, as it could get mixed up with "local trees". I prefer "direct-inheritance" (versus "samnple-resolved" inheritance). This PR attempts to reword it in that way.

Remove "local" as an edge annotation description

---

paper.tex

I have tried to make the link between sample-resolving big ARGs, and (more importantly) forwards simulations, more explicit, as well as giving a tee-up into the simplification section.

Rejig and condense text about "big" ARGs etc

---

argutils/viz.py
illustrations.py

If we have RE and red and CA as blue, that's more colourblind friendly. We can then use green for genomes (alliterative!) which will help in the cellular diagram too.
We can then change the colour scheme for coalescent ARGs so that nodes with lots of parents (representing lots of recombination) get redder, whereas nodes with only one parent are still green. I think this new scheme ticks all the boxes, although we could revert to black oval outlines in fig 3 if we don't like the proliferation of colours.

Change colour scheme

---

paper.tex

Added description of fig 5 to the caption including info about:
- edge colors (reflects child node time)
- edge width (reflects edge span)
- node colours (reflects number of parents)
- node brightness (reflects prop of node span where it is coalescent)
- Visualization below ARG (rows=edges, position along genome, vertical lines are breakpoints)
I tried to keep it brief, but there's a lot going on in this figure so the caption is pretty long... Any thoughts?

complete fig 5 caption

---

paper.tex

To address Andrew's [comment number 3](https://github.com/tskit-dev/what-is-an-arg-paper/issues/365) (we refer to fig 1 which is a gARG), my thoughts (we don't want to emphasise gARG vs eARG too much here, as you *could* create a prospective eARG, even though people don't, for good reason), and (partially) Gideon's comments about when prospective ARGs might be useful (I just mentioned forward simulations higher up).
No need to merge this yet, as I know that Jerome may disagree with some of it, but PRed so that we have something on which to base a discussion.

Second pass at prospective/retrospective

---

paper.tex

This is stacked on top of #378 and is my attempt to 
a) tie together the "retrospective vs prospective" and "converting and eARG to a gARG" sections, which both talk about simplification / Hudson. I have tried to use the mention of "ancestral material" to act as a lead-in from the first to the second.
b) clarify that converting an eARG to a gARG does not *have* to involve sample-resolving (and in fact, we would normally simulate the sample-resolved form directly). I.e. eARG -> gARG is just one step. Sample resolving is a further (lossy) "option", which helps with efficiency. My previous worry was:
> The conversion process from eARG to gARG is only the first of the two steps in the figure. The second step is a lossy one from a gARG to another sort of gARG (a sample resolved one) ...
As …

Converting eARG to gARG - reprise

---

paper.tex

I have added table for gARG to address #348.
I have also added labels for all sections. To the best of my ability, I replaced all `see Section XXX` or `see  Appendix XXX` with section labels. For this to make sense, I switched from `\section*{}` to `\section{}`. Otherwise there is no section number to refer to and LaTeX produces `see Section _blank_`.
I have also sorted Appendix Figure and Table style to `AX`, where `X` is a number. It's easy to change to `SX` but since we talk about appendices I used `AX`.

Adding tables for gARG #348 and other bits

---

paper.tex

I compressed appendix D down to the two main points (I think) it was trying to make. Paragraph 1 is about tagging events, and paragraph two is about the reality of polytomies and mutational information required to distinguish them.
What I deleted (I believe) was redundant either because the information was already in the figure caption, or unecesseary/inaccurate argumentation.
Polytomies are not enabled by the gARG view - there is absolutely no reason you couldn't have them in an eARG. Statements about approximations have already been made elsewhere.

Compress Appendix D

---

paper.tex

Addresses @hyanwong's point in overleaf  - good to slip the point in here that the encoding is ambiguous

Clarify eARG amibiguity
